[package]
name = "ping-util-rs"
version = "0.2.0"
authors = ["Dishon Merkhai <merkhai@dishon.ca>"]
edition = "2018"

[dependencies]
structopt = "0.3.13"
lazy_static = "1.4.0"
failure = "0.1.7"
smoltcp = "0.6.0"
